### ISSUE TITLE
How to style the calendar icon?

### ISSUE THREAD

**Issue by jdavidbakr** [NativeScript/nativescript-datetimepicker#59]
Apologies if this is in the docs, but I can't find it ... I have a screen that has a dark background and have styled the `<DatePickerField />` to be white text.  However, the calendar icon remains black.  How do I change the color of the icon?

<img width="349" alt="iPhone_8_—_13_2_2" src="https://user-images.githubusercontent.com/25177/70019447-1dc7a400-153e-11ea-97f5-6c80e99a16f9.png">

**Comment by bundyo** [comment]
Unfortunately you can't just change the color - this icon is a background image. There is styling for it in the {N} Theme 2.0, so you can probably use that. If you don't plan on using it, you can just rip it off from there and use it:

```css
.ns-dark DatePickerField {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFQAAAAwBAMAAAB9IEC+AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURUdwTP///////////////xPgMRoAAAAEdFJOUwDAECBTkMJDAAAAV0lEQVRIx2NgIBW4uLigMeinlEnEBQM4KmBVyuiCBQhgVcqCTakzDqUKGG51ccChlIFWStHDboQpxQLoq3Q0CgaRUhZoVI0qHblKB3tBREJlREIVRwsAALYjaEQQIFg+AAAAAElFTkSuQmCC');
}
```

If you don't want to support two modes - remove the .ns-dark in front of it.
